### ISSUE TITLE
No detection with custom obj of keyboard as well as with demo bag and model file

### ISSUE THREAD

**Issue by mrtnbm** [ammar-n-abbas/FoundationPoseROS2#3] opened 2024-11-08 17:43 UTC
I set up a obj of my keyboard that has the right dimensions and similar colors. Still, I can't seem to get a successful pose estimation. 

 Here is the obj, just put into a zip to be able to upload it here:
[logi_wo_mtl_vert_col.zip](https://github.com/user-attachments/files/17682102/logi_wo_mtl_vert_col.zip)

The mask looks like this:
![masks](https://github.com/user-attachments/assets/06b92f23-6620-4178-a688-f11429cffe65)

RGB looks like this (light and therefore video quality might be bad, is this the cause maybe?):

![image](https://github.com/user-attachments/assets/5276da16-7bc4-4c8d-8a33-1273d01a916b)

I only selected this object with mouse click and pressing Enter afterwards. As soon as the tracking gui starts, I do not see any pose estimation happening. 

I use Ubuntu 22.04 with 4090 Mobile GPU and conda with Python 3.10 env and Intel Realsense D435 with 5.13.0.5 FW (there is 5.16.0.1 released, did not try yet because Isaac Ros needs this FW):
```shell
CUDA Toolkit 12.5, Driver 12.6
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4090 Laptop GPU" (16 GiB, sm_89, mempool enabled)
```
I noticed that I get some errors, right after selecting the object in segmentation mask:
```shell
QObject::moveToThread: Current thread (0x26e64200) is not the object's thread (0x2a1cca90).
Cannot move to target thread (0x26e64200)
.
. occurs for a lot of times
.
```
After hitting enter and starting the tracking module, the errors come up again: 

```shell
[INFO] [1731086589.851515483] [pose_estimation_node]: Object 0 selected.
[reset_object()] self.diameter:0.44027072379730176, vox_size:0.02201353618986509
[reset_object()] self.pts:torch.Size([186, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
num original candidates = 252
num of pose after clustering: 252
[make_rotation_grid()] after cluster, rot_grid:(252, 4, 4)
[make_rotation_grid()] self.rot_grid: torch.Size([252, 4, 4])
[register()] Welcome
Module Utils 64702ec load on device 'cuda:0' took 0.26 ms  (cached)
[register()] poses:(252, 4, 4)
[register()] after viewpoint, add_errs min:-1.0
/home/mb/miniconda3/envs/launcher/lib/python3.10/site-packages/torch/__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] trans_normalizer:[0.019999999552965164, 0.019999999552965164, 0.05000000074505806], rot_normalizer:0.3490658503988659
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
/home/mb/miniconda3/envs/launcher/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] warp done
[make_crop_data_batch()] pose batch data done
[predict()] forward start
[predict()] forward done
[predict()] ob_in_cams:(252, 4, 4)
[predict()] self.cfg.use_normal:False
[predict()] making cropped data
[make_crop_data_batch()] Welcome make_crop_data_batch
[make_crop_data_batch()] make tf_to_crops done
[make_crop_data_batch()] render done
[make_crop_data_batch()] pose batch data done
[find_best_among_pairs()] pose_data.rgbAs.shape[0]: 252
[predict()] forward done
[register()] final, add_errs min:-1.0
[register()] sort ids:tensor([  0,   6,  30,  72,  96, 102, 222, 132, 198, 126, 168,   3,   9,  75,  99, 105, 135, 144,  84, 120, 129, 150, 171, 174,  12,  18,  78,  90, 114, 147, 191, 207, 228,  15,  21,  81,  87,  93, 117, 123, 231,  97, 153, 204, 201,  91, 107, 173,  24,  39,  33, 175, 177, 208, 241,  27, 155, 223, 225,  45, 118, 136,
        166, 230,  36, 170, 236, 239, 111, 188, 203, 244,  42, 108, 141, 161, 184, 226, 218,  70, 181, 152, 138, 237,  58, 215,  16,  17,  19,  79,  82, 192, 221,   2,  10,  11,  20,  67,  68,  74,  80, 106, 121, 163, 176,   1,  73,  76,  77,  83,  88,  89, 214,  98, 127, 128, 156,  56, 115, 122, 172,  28,  55,  65,
         94,  95, 100, 104, 116, 119, 145, 148, 158, 238,  14,  29,  37,  38,  40,  92, 101, 124, 189, 190, 212,   5,  13,  22,  23,  25, 103, 134, 157, 185, 195, 199, 213, 233,   4,   7,   8,  34,  35,  44,  46,  64,  71,  85,  86, 125, 130, 137, 149, 151, 160, 182, 200, 211, 216, 232, 235, 245, 246,  26,  31,  41,
         49,  52, 133, 164, 180, 196, 249,  32,  43,  53,  61,  69, 131, 159, 165, 178, 179, 193, 206, 210, 217, 227, 234, 240,  47,  59,  62, 143, 154, 162, 187, 194, 202, 209, 220, 224, 242, 243, 251,  63, 110, 112, 113, 140, 146, 183, 186, 229, 250, 139, 142, 169, 205, 247,  50, 167,  51,  60,  66, 109, 197, 219,
         48,  54,  57, 248])
[register()] sorted scores:tensor([63.9375, 63.9375, 63.9375, 63.9375, 63.9375, 63.9375, 63.9375, 63.9062, 63.9062, 63.8750, 63.7500, 63.5938, 63.5625, 63.5625, 63.5625, 63.5625, 63.5625, 63.5625, 63.5312, 63.5312, 63.5312, 63.5312, 63.5312, 63.5312, 63.5000, 63.5000, 63.5000, 63.5000, 63.5000, 63.5000, 63.5000, 63.4688, 63.4688, 63.4375,
        63.4375, 63.4375, 63.4375, 63.4375, 63.4375, 63.4375, 63.4375, 63.3750, 63.3438, 63.3438, 63.3125, 63.2812, 63.2812, 63.2812, 63.2500, 63.2500, 63.2188, 63.2188, 63.2188, 63.2188, 63.2188, 63.1875, 63.1875, 63.1875, 63.1875, 63.1562, 63.1562, 63.1562, 63.1562, 63.1562, 63.1250, 63.1250, 63.1250, 63.1250,
        63.0938, 63.0938, 63.0938, 63.0625, 63.0000, 63.0000, 63.0000, 63.0000, 63.0000, 63.0000, 62.8750, 62.8438, 62.8438, 62.7812, 62.7500, 62.7500, 62.7188, 62.6875, 62.6250, 62.5938, 62.5938, 62.5938, 62.5938, 62.5938, 62.5938, 62.5625, 62.5625, 62.5625, 62.5625, 62.5625, 62.5625, 62.5625, 62.5625, 62.5625,
        62.5625, 62.5625, 62.5625, 62.5312, 62.5312, 62.5312, 62.5312, 62.5312, 62.5312, 62.5312, 62.5312, 62.5000, 62.5000, 62.5000, 62.5000, 62.4688, 62.4688, 62.4688, 62.4688, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4375, 62.4062, 62.4062,
        62.4062, 62.4062, 62.4062, 62.4062, 62.4062, 62.4062, 62.4062, 62.4062, 62.4062, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3750, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438,
        62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3438, 62.3125, 62.3125, 62.3125, 62.3125, 62.3125, 62.3125, 62.3125, 62.3125, 62.3125, 62.3125, 62.2812, 62.2812, 62.2812, 62.2812, 62.2812, 62.2812, 62.2812, 62.2812, 62.2812, 62.2812, 62.2812,
        62.2812, 62.2812, 62.2812, 62.2812, 62.2812, 62.2812, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2500, 62.2188, 62.2188, 62.2188, 62.2188, 62.2188, 62.2188, 62.2188, 62.2188, 62.2188, 62.2188, 62.1875, 62.1875, 62.1875,
        62.1875, 62.1875, 62.1562, 62.1562, 62.1250, 62.1250, 62.1250, 62.1250, 62.1250, 62.1250, 62.0938, 62.0938, 62.0938, 62.0625])
QObject::moveToThread: Current thread (0x26e64200) is not the object's thread (0x2a1cca90).
Cannot move to target thread (0x26e64200)

QObject::moveToThread: Current thread (0x26e64200) is not the object's thread (0x2a1cca90).
Cannot move to target thread (0x26e64200)

QObject::moveToThread: Current thread (0x26e64200) is not the object's thread (0x2a1cca90).
Cannot move to target thread (0x26e64200)

QObject::moveToThread: Current thread (0x26e64200) is not the object's thread (0x2a1cca90).
Cannot move to target thread (0x26e64200)
```
Also, I had to change `trimesh.load()` line to add arguments for forcing mesh: `trimesh.load(mesh, force='mesh', process=False)`

Otherwise I got AttributeErrors for missing vertices parameter in the scene (I only have one model in the file, do not know why trimesh added in a scene). I do not know if process=False is really necessary.

**Comment by ammar-n-abbas** [comment] 2024-11-09 22:18
No, the output mask image does not seem to be the right one.

Have you used "sam2_b.pt" model? The one you have showed looks like the FastSAM("FastSAM-s.pt") model.

**Comment by ammar-n-abbas** [comment] 2024-11-10 09:57
can you show the window of "click on objects to track"

**Comment by ammar-n-abbas** [comment] 2024-11-13 16:12
Can you make sure please that there are no overlapping segmentations that intersect each other's boundaries.

**Comment by ammar-n-abbas** [comment] 2024-11-13 23:13
can you share the video recording of the testing?

**Comment by vmayoral** [comment] 2024-11-14 09:27
First off, kudos to the author for this repo. There's both research and engineering value in what's been done here.

I'd like to report I get similar behavior and issues than the one reported by @mrtnbm and @mres [here](https://github.com/ammar-n-abbas/FoundationPoseROS2/issues/6#issuecomment-2475624621). For simplified reproduction, I used also the provided rosbag obtaining the same issue: there's no pose detected for the cube.

My setup uses `ROS 2 Humble`, `Ubuntu 22.04` an `AMD Ryzen 5 PRO 4650G` CPU and an NVIDIA `GeForce RTX 3060`.

**Comment by ammar-n-abbas** [comment] 2024-11-14 12:51
There was a minor bug in the code which has been fixed now, apologies for that.
The demo data rosbag screen recorded has now been updated in the Readme along with the terminal log.

**Closed as completed** 2024-11-14 14:11 UTC

**Comment by vmayoral** [comment] 2024-11-14 14:18
I didn't quite manage to reproduce it. Various issues/errors while rebuilding. Would it help if I dockerized the whole process @ammar-n-abbas?

**Comment by ammar-n-abbas** [comment] 2024-11-14 14:22
> Hey @ammar-n-abbas I could fix the issue by changing the logic as follows as well:
> 
> ```python
>             if self.i != 0:
>             # if pose_est.is_register:
>                 pose = pose_est.track_one(rgb=color, depth=depth, K=self.cam_K, iteration=args.track_refine_iter)
>                 center_pose = pose @ np.linalg.inv(to_origin)
> 
>                 self.publish_pose_stamped(center_pose, f"object_{idx}_frame", f"/Current_OBJ_position_{idx+1}")
> 
>                 visualization_image = self.visualize_pose(visualization_image, center_pose, idx)
>             if self.i == 0:
>                 pose = pose_est.register(K=self.cam_K, rgb=color, depth=depth, ob_mask=obj_mask, iteration=args.est_refine_iter)
>             self.i += 1
> ```

unfortunately this logic would not work for multiple objects. I am trying to modify the function after calling to avoid replacing the file due to license issue

**Comment by ammar-n-abbas** [comment] 2024-11-14 14:24
> I didn't quite manage to reproduce it. Various issues/errors while rebuilding. Would it help if I dockerized the whole process @ammar-n-abbas?

@vmayoral the only reason to build conda was to be able to customize it with ROS etc. but for sure it can be dockerized.

**Comment by vmayoral** [comment] 2024-11-14 14:27
@ammar-n-abbas, makes sense.
Just trying to be helpful in the reproduction of the issues. Let me retry without the dockerization then.

For some reason, It's getting stucked here:

```bash
[__init__()] self.h5_file:
[__init__()] Using pretrained model from /home/xilinx/foundationpose_ros_ws/src/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
```

I understand it should take a while, but after recent changes, it just doesn't advance anymore (10+ minutes of wait, several times).

**Comment by vmayoral** [comment] 2024-11-14 14:28
Got it, let me clean-up and retry. Lots of changes and uncertainty. Thanks! Will re-do.

**Comment by mcres** [comment] 2024-11-14 14:44
@ammar-n-abbas thanks for the effort, I've been able to reproduce the example as well. However, I had to make the changes highlighted below to `foundationpose_ros_multi.py`:
1. AFAIK, you need to make further updates to use SAM 2.1 apart from the segmentation model being used (ref [here](https://colab.research.google.com/github/facebookresearch/sam2/blob/main/notebooks/image_predictor_example.ipynb))
2. `debug_dir` default value forces the user to have `sudo` permissions to write under the `/home` directory.
 
```diff
@@ -126,7 +126,7 @@ class PoseEstimationNode(Node):
         self.glctx = dr.RasterizeCudaContext()
 
         # Initialize SAM2 model
-        self.seg_model = SAM("sam2.1_b.pt")
+        self.seg_model = SAM("sam2_b.pt")
 
         self.pose_estimations = {}  # Dictionary to track multiple pose estimations
         self.pose_publishers = {}  # Dictionary to store publishers for each object
@@ -219,7 +219,8 @@ class PoseEstimationNode(Node):
                                 mesh=temp_mesh,
                                 scorer=self.scorer,
                                 refiner=self.refiner,
-                                glctx=self.glctx
+                                glctx=self.glctx,
+                                debug_dir='./FoundationPose'
                             )
 
                             temporary_pose_estimations[sequential_id] = {
```

**Comment by ammar-n-abbas** [comment] 2024-11-14 14:49
Perfect, I'll merge the changes 

Sam2.1 models are the most up to date ones which require ultralyrics>=8.3.0 that has been updated in the requirements

**Comment by mcres** [comment] 2024-11-14 15:04
Hmm, weird. Using `ultralytics==8.3.1` as specified in the `requirements.txt`, I get the following error when using `sam2.1_b`:

```bash
Traceback (most recent call last):
  File "/home/martinho/acceleration/foundation_pose_ws/src_2/FoundationPoseROS2/foundationpose_ros_multi.py", line 377, in <module>
    main()
  File "/home/martinho/acceleration/foundation_pose_ws/src_2/FoundationPoseROS2/foundationpose_ros_multi.py", line 371, in main
    node = PoseEstimationNode(new_file_paths)
  File "/home/martinho/acceleration/foundation_pose_ws/src_2/FoundationPoseROS2/foundationpose_ros_multi.py", line 130, in __init__
    self.seg_model = SAM("sam2.1_b.pt")
  File "/home/martinho/.local/lib/python3.10/site-packages/ultralytics/models/sam/model.py", line 67, in __init__
    super().__init__(model=model, task="segment")
  File "/home/martinho/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 145, in __init__
    self._load(model, task=task)
  File "/home/martinho/.local/lib/python3.10/site-packages/ultralytics/models/sam/model.py", line 84, in _load
    self.model = build_sam(weights)
  File "/home/martinho/.local/lib/python3.10/site-packages/ultralytics/models/sam/build.py", line 350, in build_sam
    raise FileNotFoundError(f"{ckpt} is not a supported SAM model. Available models are: \n {sam_model_map.keys()}")
FileNotFoundError: sam2.1_b.pt is not a supported SAM model. Available models are: 
 dict_keys(['sam_h.pt', 'sam_l.pt', 'sam_b.pt', 'mobile_sam.pt', 'sam2_t.pt', 'sam2_s.pt', 'sam2_b.pt', 'sam2_l.pt'])
```

**Comment by ammar-n-abbas** [comment] 2024-11-14 15:31
yes sorry it is >= 8.3.22

**Comment by ammar-n-abbas** [comment] 2024-11-14 15:41
> > Hey @ammar-n-abbas I could fix the issue by changing the logic as follows as well:
> > ```python
> >             if self.i != 0:
> >             # if pose_est.is_register:
> >                 pose = pose_est.track_one(rgb=color, depth=depth, K=self.cam_K, iteration=args.track_refine_iter)
> >                 center_pose = pose @ np.linalg.inv(to_origin)
> > 
> >                 self.publish_pose_stamped(center_pose, f"object_{idx}_frame", f"/Current_OBJ_position_{idx+1}")
> > 
> >                 visualization_image = self.visualize_pose(visualization_image, center_pose, idx)
> >             if self.i == 0:
> >                 pose = pose_est.register(K=self.cam_K, rgb=color, depth=depth, ob_mask=obj_mask, iteration=args.est_refine_iter)
> >             self.i += 1
> > ```
> 
> unfortunately this logic would not work for multiple objects. I am trying to modify the function after calling to avoid replacing the file due to license issue

@mrtnbm I have updated the code with the last commit to directly modify the class and function attributes without changing the source estimator file. Can you please verify if it works?

Thanks

**Comment by mcres** [comment] 2024-11-14 15:42
Ok, `ultralytics` version was the issue. Thanks for pointing it out.
